apiVersion: apps/v1
kind: Deployment
metadata:
  name: liqo-nodebind
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: liqo-nodebind
  template:
    metadata:
      labels:
        app: liqo-nodebind
    spec:
      serviceAccountName: liqo-nodebind
      {{ if .Values.deployment.image.pullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.deployment.image.pullSecret.name }}
      {{- end }}
      containers:
        - name: liqo-nodebind
          image: {{ .Values.deployment.image.repository }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.deployment.container.resources }}
          resources:
            {{- toYaml .Values.deployment.container.resources | nindent 12 }}
          {{- end }}
          args:
            - --namespace={{ .Release.Namespace }}
            - --secret-name=liqo-nodebind-webhook
            - --webhook-port=9443
            - --metrics-addr=:{{ .Values.deployment.container.args.metricsPort }}
            - --probe-addr=:{{ .Values.deployment.container.args.probePort }}
            - --klog.v={{ .Values.deployment.container.args.verbosity }}
          ports:
            - name: webhook
              containerPort: {{ .Values.deployment.container.args.webhookPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.deployment.container.args.metricsPort }}
              protocol: TCP
            - name: probe
              containerPort: {{ .Values.deployment.container.args.probePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.deployment.container.args.probePort }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.deployment.container.args.probePort}}


