{{- if .Values.nodeMonitor.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-node-monitor
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-node-monitor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: myrtus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-node-monitor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-node-monitor
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "myrtus-monitor.serviceAccountName" . }}
      {{- if .Values.image.pullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret.name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: node-monitor
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - node-monitor
        args:
          - "--node-name=$(NODE_NAME)"
          - "--node-type={{ .Values.nodeMonitor.nodeType }}"
          - "--liqo-cluster-id={{ .Values.global.liqoClusterId }}"
          - "--kb-endpoint={{ .Values.global.kbEndpoint }}"
          - "--log-level={{ .Values.common.logLevel }}"
          - "--default-timeout={{ .Values.common.defaultTimeout }}"
          - "--default-period={{ .Values.common.defaultPeriod }}"
          {{- if .Values.nodeMonitor.activeCollectors }}
          - "--active-collectors={{ join " " .Values.nodeMonitor.activeCollectors }}"
          {{- end }}
          {{- if .Values.nodeMonitor.excludeCollectors }}
          - "--exclude-collectors={{ join " " .Values.nodeMonitor.excludeCollectors }}"
          {{- end }}
          {{- if .Values.nodeMonitor.kbDisabled }}
          - "--kb-disabled"
          {{- end }}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DKB_URL
            value: {{ .Values.global.kbEndpoint }}
        resources:
          {{- toYaml .Values.nodeMonitor.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
